#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700 """

import argparse
import json
import select
import socket

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:
  """ Your Router """
  def __init__(self, asn, networks):
    self.asn = asn
    self.routes = [] # Routing Table (list of dictionaries containing routing info)
    self.updates = []
    self.revokes = []
    self.relations = {}
    self.sockets = {}
    for relationship in networks:
      network, relation = relationship.split("-")
      self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
      self.sockets[network].setblocking(0)
      self.sockets[network].connect(network)
      self.relations[network] = relation

  def lookup_routes(self, daddr):
    """ Lookup all valid routes for an address """
    # TODO
    # dictionary of lists of routes. key is length of bit match
    outroutes = { 0: [] }
    longest_match = 0
    for entry in self.routes:
      netmask = entry[NMSK]
      network = entry[NTWK]

      netmask_split = netmask.split('.')

      network_split = network.split('.')
      network_convert = ""
      for i in network_split:
        network_convert += format(int(i), "08b")

      address_split = daddr.split('.')
      address_convert = ""
      for i in address_split:
        address_convert += format(int(i), "08b")
      
      mask_match = True
      for i in range(len(netmask_split)):
        # Updated for bit masks
        if netmask_split[i] == '255':
          if not network_split[i] == address_split[i]:
            mask_match = False
            continue
          else:
            if netmask_split[i] != '0':
              mask_split_length = len(format(int(netmask_split[i]), "08b").strip("0"))
              if not network_convert[i*8:i*8+mask_split_length] == address_convert[i*8: i*8+mask_split_length]:
                mask_match = False

      match_length = 0
      if mask_match:
        for i in range(len(network_convert)):
          if network_convert[i] == address_convert[i]:
            match_length += 1
          else:
            break
        if match_length not in outroutes:
          outroutes[match_length] = []
        outroutes[match_length].append(entry)
        if match_length > longest_match:
          longest_match = match_length

    return outroutes[longest_match]

  def get_shortest_as_path(self, routes):
    """ select the route with the shortest AS Path """
    # TODO
    outroutes = []
    as_length = 100 
    for entry in routes:
      if as_length > len(entry[APTH]):
        as_length = len(entry[APTH])

    for entry in routes:
      if as_length == len(entry[APTH]):
        outroutes.append(entry)
    return outroutes

  def get_highest_preference(self, routes):
    """ select the route with the highest localpref """
    # TODO
    highest_lpref = 0
    outroutes = []
    for entry in routes:
      if entry[LPRF] > highest_lpref:
        highest_lpref = entry[LPRF]
    
    for entry in routes:
      if entry[LPRF] == highest_lpref:
        outroutes.append(entry)
    
    return outroutes

  def get_self_origin(self, routes):
    """ select self originating routes """
    # TODO
    outroutes = []
    for entry in routes:
      if entry[SORG]:
        outroutes.append(entry)
    if not outroutes:
      for entry in routes:
        outroutes.append(entry)
    return outroutes

  def get_origin_routes(self, routes):
    """ select origin routes: EGP > IGP > UNK """
    #assuming they meant IGP > EGP > UNK
    # TODO
    outroutes = []
    for entry in routes:
      if entry[ORIG] == "IGP":
        outroutes.append(entry)
    if len(outroutes) != 0:
      return outroutes
    for entry in routes:
      if entry[ORIG] == "EGP":
        outroutes.append(entry)
    if len(outroutes) != 0:
      return outroutes
    for entry in routes:
      if entry[ORIG] == "UNK":
        outroutes.append(entry)
    return outroutes

  # return 1 if the first of two split ips is lower, 2 if the second is (return 1 if equal)
  def compare_split_ips(self, first, second):
    for i in range(len(first)):
      if i > len(second):
        return 2
      if first[i] < second[i]:
        return 1
      if second[i] < first[i]:
        return 2

    return 1

  def get_lowest_ip(self, routes):
    #only checks first # in ip address. should probably be changed
    ips = []
    ips_split = []
    #index of lowest ip in list
    lowest = 0
    if not routes:
      return []
    for entry in routes:
      ips.append(entry[PEER])
    for ip in ips:
      ips_split.append(ip.split('.'))
    for index in range(len(ips_split)):
        if self.compare_split_ips(ips_split[lowest], ips_split[index]) == 2:
          lowest = index

    return [routes[lowest]]

  def filter_relationships(self, srcif, routes):
    """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
    outroutes = []
   
    for item in routes:
      source_type = self.relations[srcif]
      dest_type = self.relations[item[PEER]]
      if (source_type == PEER or source_type == PROV) and (dest_type == PEER or dest_type == PROV):
        continue
      outroutes.append(item)
        
    return outroutes

  def get_route(self, srcif, daddr):
    """ Select the best route for a given address """
    # TODO
    peer = None
    routes = self.lookup_routes(daddr)
    # Rules go here
    if routes:
      # 1. Highest Preference
      routes = self.get_highest_preference(routes)
      # 2. Self Origin
      routes = self.get_self_origin(routes)
      # 3. Shortest ASPath
      routes = self.get_shortest_as_path(routes)
      # 4. EGP > IGP > UNK
      routes = self.get_origin_routes(routes)
      # 5. Lowest IP Address
      # TODO
      routes = self.get_lowest_ip(routes)
      # Final check: enforce peering relationships
      routes = self.filter_relationships(srcif, routes)

    if not routes:
      return []
    peer = routes[0][PEER]
    return peer
  def forward(self, srcif, packet):
    """ Forward a data packet """
    # TODO
    check = self.get_route(srcif, packet[DEST])
    if not check:
      self.send_error(srcif, packet)
    else:
      
      packet_convert = bytes(json.dumps(packet), 'ascii')
      self.sockets[check].sendall(packet_convert)

    return True

  def compare_adj(self, o, t): #one and two
    #are the IPs numerically adjacent 
    if t[NMSK] != o[NMSK]:
      return False
    else:
      o_netmask_split = o[NMSK].split('.')
      o_network_split = o[NTWK].split('.')

      t_netmask_split = t[NMSK].split('.')
      t_network_split = t[NTWK].split('.')

      o_network_convert = ""
      for i in o_network_split:
        o_network_convert += format(int(i), "08b")

      t_network_convert = ""
      for i in t_network_split:
        t_network_convert += format(int(i), "08b")
      
      o_netmask_convert = ""
      for i in o_netmask_split:
        o_netmask_convert += format(int(i), "08b")

      t_netmask_convert = ""
      for i in t_netmask_split:
        t_netmask_convert += format(int(i), "08b")
     
      o_network_convert = o_network_convert[0:len(o_netmask_convert.strip("0"))]
      t_network_convert = t_network_convert[0:len(t_netmask_convert.strip("0"))]

      o_network_convert = o_network_convert[:-1]
      t_network_convert = t_network_convert[:-1]   
      if o_network_convert == t_network_convert:
        return True

  def coalesce(self):
    """ coalesce any routes that are right next to each other """
    # TODO (this is the most difficult task, save until last)
    index_to_del = []
    routes_to_add = []

    for entry_index in range(len(self.routes)):
      if entry_index in index_to_del:
        continue
      entry = self.routes[entry_index]
      comp_routes = self.lookup_routes(entry[NTWK])
       
      adj = False #are they numerically adjacent?
      snh = False #same next hop?
      att = False #same attributes?
      for compare_index in range(len(self.routes)):
        if compare_index in index_to_del:
          continue
        compare = self.routes[compare_index]
        if entry == compare: #this will repeat some comparisons but it should still work
          continue #skip comparing it to itself
        adj = self.compare_adj(entry, compare)
        if entry[PEER] == compare[PEER]:
          snh = True
        if entry[LPRF] == compare[LPRF]:
          if entry[SORG] == compare[SORG]:
            if entry[APTH] == compare[APTH]:
              if entry[ORIG] == compare[ORIG]:
                att = True
        if snh and att and adj:
          #the logic to see if a route should be agg'd works 
          #aggregate it
          #Trying to make new entry for routing table (don't forget to remove the old entries, which you can access here with entry and compare)
          index_to_del.append(entry_index)
          index_to_del.append(compare_index)

          netmask_split = entry[NMSK].split('.')
          network_split = entry[NTWK].split('.')

          network_convert = ""
          for i in network_split:
            network_convert += format(int(i), "08b")

          netmask_convert = ""
          for i in netmask_split:
            netmask_convert += format(int(i), "08b")

          new_mask_length = len(netmask_convert.strip("0")) - 1
          netmask_convert = netmask_convert[:new_mask_length] + "0" + netmask_convert[new_mask_length + 1:]
          network_convert = network_convert[:new_mask_length] + "0" + network_convert[new_mask_length + 1:]

          network_convert_final = ""
          netmask_convert_final = ""
          for i in range(int(len(network_convert)/8)):
            network_convert_final += int(network_convert[i*8:(i+1)*8], 2)
            netmask_convert_final += int(netmask_convert[i*8:(i+1)*8], 2)
            if i != (len(network_convert)/8) - 1 :
              network_convert_final += "."
              netmask_convert_final += "."

          new_route = {NTWK: network_convert_final,
                       NMSK: netmask_convert_final,
                       LPRF: entry[LPRF],
                       SORG: entry[SORG],
                       APTH: entry[APTH],
                       ORIG: entry[ORIG],
                       PEER: entry[PEER]}
          routes_to_add.append(new_route)
          break # this entry has been aggregated

    index_to_del.sort(reverse=True)
    for index in index_to_del:
      del self.routes[index]
    for route in routes_to_add:
      self.routes.append(route)

    if len(routes_to_add) > 0:
      self.coalesce()

    return True

  # disaggregate any routes with netmasks containing numbers other than 255 or 0
  def disaggregate(self):
    index_to_del = []
    routes_to_add = []
    for index in range(len(self.routes)):
      route = self.routes[index]
      mask_split = route[NMSK].split(".")
      is_agg = False
      section_index = 0
      new_mask_length = 0

      for i in range(len(mask_split)):
        if mask_split[i] != "255" and mask_split[i] != "0":
          is_agg = True
          section_index = i
          mask_split_convert = format(mask_split[i], "08b")
          new_mask_length = len(mask_split_convert.strip("0")) + 1
          mask_split[i] = int(mask_split_convert[:new_mask_length] + "1" + mask_split_convert[new_mask_length + 1:], 2)
          break

      if not is_agg:
        continue

      network_split = route[NTWK].split(".")
      net_split_convert = format(mask_split[section_index], "08b")
      first_val = int(net_split_convert[:new_mask_length] + "0" + net_split_convert[new_mask_length + 1:], 2)
      second_val = int(net_split_convert[:new_mask_length] + "0" + net_split_convert[new_mask_length + 1:], 2)

      first_network = ""
      second_network = ""
      new_mask = ""
      for i in range(len(network_split)):
        new_mask += mask_split[i]
        if i == section_index:
          first_network += first_val
          second_network += second_val
        else:
          first_network += network_split[i]
          second_network += network_split[i]
        if i != len(network_split) - 1:
          first_network += "."
          second_network += "."
          new_mask += "."

      first_route = {NTWK: first_network,
                     NMSK: new_mask,
                     LPRF: route[LPRF],
                     SORG: route[SORG],
                     APTH: route[APTH],
                     ORIG: route[ORIG],
                     PEER: route[PEER]}

      routes_to_add.append(first_route)
      second_route = first_route
      second_route[NTWK] = second_network
      routes_to_add.append(second_route)
      index_to_del.insert(0, index)

    for i in index_to_del:
      del self.routes[i]

    for i in routes_to_add:
      self.routes.append(i)

    if len(routes_to_add) > 0:
      self.disaggregate()


  def update(self, srcif, packet):
    """ handle update packets """
    # TODO
    new_apath = packet[MESG][APTH]
    new_apath.append(self.asn)
    update_info = {NTWK: packet[MESG][NTWK],
                   NMSK: packet[MESG][NMSK],
                   LPRF: packet[MESG][LPRF],
                   SORG: packet[MESG][SORG],
                   APTH: new_apath,
                   ORIG: packet[MESG][ORIG]}
    self.updates.append(update_info)

    route_info = update_info
    route_info[PEER] = srcif
    self.routes.append(route_info)

    for network in self.sockets:
      if network == srcif:
        continue
      if not self.relations[srcif] == CUST:
        if self.relations[network] != CUST:
          continue
      new_packet = {SRCE: network[:-1] + '1',
                    DEST: network,
                    TYPE: UPDT,
                    MESG: update_info}

      new_packet_convert = bytes(json.dumps(new_packet), 'ascii')
      
      self.sockets[network[:-1] + '2'].sendall(new_packet_convert)
    self.coalesce()
    return True

  def revoke(self, srcif, packet):
    """ handle revoke packets """
    #won't work with coalesce as is. disaggregation is required
    self.disaggregate()

    for item in packet[MESG]:
      revoke_info = {NTWK: item[NTWK],
                     NMSK: item[NMSK]}
      self.revokes.append(revoke_info)
      indexes_to_del = []
      for index in range(len(self.routes)):
        if self.routes[index][NTWK] == revoke_info[NTWK] and self.routes[index][NMSK] == revoke_info[NMSK] and self.routes[index][PEER] == srcif:
          indexes_to_del.insert(0, index)
      
      for i in indexes_to_del:
        del self.routes[i]
    for network in self.sockets:
      if network == srcif:
        continue
      new_packet = {SRCE: network[:-1] + '1',
                    DEST: network,
                    TYPE: RVKE,
                    MESG: packet[MESG]}

      new_packet_convert = bytes(json.dumps(new_packet), 'ascii')
      
      self.sockets[network[:-1] + '2'].sendall(new_packet_convert)

    self.coalesce()
    return True

  def dump(self, packet):
    """ handles dump table requests """
    msg = []
    response = {SRCE: packet[DEST], DEST: packet[SRCE], TYPE: 'table'}
    for entry in self.routes:
      row = {NTWK: entry[NTWK], NMSK: entry[NMSK], PEER: entry[PEER]}
      msg.append(row)
    response[MESG] = msg
    response_convert = bytes(json.dumps(response), 'ascii')
    self.sockets[packet[SRCE][:-1] + '2'].sendall(response_convert)
    return True

  def handle_packet(self, srcif, packet):
    """ dispatches a packet """
    if packet[TYPE] == UPDT:
      return self.update(srcif, packet)
    elif packet[TYPE] == DATA:
      return self.forward(srcif, packet)
    elif packet[TYPE] == RVKE:
      return self.revoke(srcif, packet)
    elif packet[TYPE] == DUMP:
      return self.dump(packet)
    else:
        return False
    

  def send_error(self, conn, msg):
    """ Send a no_route error message """
    # TODO
    no_route = {SRCE: conn[:-1] + '1',
                DEST: msg[SRCE],
                TYPE: NRTE,
                MESG: {}}

    no_route_convert = bytes(json.dumps(no_route), 'ascii')
    self.sockets[conn].sendall(no_route_convert)
    return

  def run(self):
    """ main loop for the router """
    while True:
      socks = select.select(self.sockets.values(), [], [], 0.1)[0]
      for conn in socks:
        try:
          k = conn.recv(65535)
        except:
          # either died on a connection reset, or was SIGTERM's by parent
          return
        if k:
          for sock in self.sockets:
            if self.sockets[sock] == conn:
              srcif = sock
          msg = json.loads(k)
          if not self.handle_packet(srcif, msg):
            self.send_error(srcif, msg)
        else:
          return

if __name__ == "__main__":
  PARSER = argparse.ArgumentParser(description='route packets')
  PARSER.add_argument('asn', type=int)
  PARSER.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
  ARGS = PARSER.parse_args()
  Router(ARGS.asn, ARGS.networks).run()
